//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrucoPrueba1.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrucoPrueba1.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ace.
        /// </summary>
        public static string CardsTextAce {
            get {
                return ResourceManager.GetString("CardsTextAce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Card.
        /// </summary>
        public static string CardsTextCard {
            get {
                return ResourceManager.GetString("CardsTextCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clubs.
        /// </summary>
        public static string CardsTextClubs {
            get {
                return ResourceManager.GetString("CardsTextClubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Five.
        /// </summary>
        public static string CardsTextFive {
            get {
                return ResourceManager.GetString("CardsTextFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Four.
        /// </summary>
        public static string CardsTextFour {
            get {
                return ResourceManager.GetString("CardsTextFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gold.
        /// </summary>
        public static string CardsTextGold {
            get {
                return ResourceManager.GetString("CardsTextGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horse.
        /// </summary>
        public static string CardsTextHorse {
            get {
                return ResourceManager.GetString("CardsTextHorse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jack.
        /// </summary>
        public static string CardsTextJack {
            get {
                return ResourceManager.GetString("CardsTextJack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a King.
        /// </summary>
        public static string CardsTextKing {
            get {
                return ResourceManager.GetString("CardsTextKing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seven.
        /// </summary>
        public static string CardsTextSeven {
            get {
                return ResourceManager.GetString("CardsTextSeven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Six.
        /// </summary>
        public static string CardsTextSix {
            get {
                return ResourceManager.GetString("CardsTextSix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sword.
        /// </summary>
        public static string CardsTextSword {
            get {
                return ResourceManager.GetString("CardsTextSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Three.
        /// </summary>
        public static string CardsTextThree {
            get {
                return ResourceManager.GetString("CardsTextThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Two.
        /// </summary>
        public static string CardsTextTwo {
            get {
                return ResourceManager.GetString("CardsTextTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to exit? Your changes will not be saved.
        /// </summary>
        public static string DialogTextConfirmationNewUser {
            get {
                return ResourceManager.GetString("DialogTextConfirmationNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This email address is already in use.
        /// </summary>
        public static string DialogTextEmailAlreadyExists {
            get {
                return ResourceManager.GetString("DialogTextEmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error loading.
        /// </summary>
        public static string DialogTextError {
            get {
                return ResourceManager.GetString("DialogTextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please fill all the fields.
        /// </summary>
        public static string DialogTextFillFields {
            get {
                return ResourceManager.GetString("DialogTextFillFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid username or password.
        /// </summary>
        public static string DialogTextInvalidUserPass {
            get {
                return ResourceManager.GetString("DialogTextInvalidUserPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email is too long.
        /// </summary>
        public static string DialogTextLongEmail {
            get {
                return ResourceManager.GetString("DialogTextLongEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password is too long.
        /// </summary>
        public static string DialogTextLongPassword {
            get {
                return ResourceManager.GetString("DialogTextLongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username is too long.
        /// </summary>
        public static string DialogTextLongUsername {
            get {
                return ResourceManager.GetString("DialogTextLongUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while registering, please try again later.
        /// </summary>
        public static string DialogTextNewUserException {
            get {
                return ResourceManager.GetString("DialogTextNewUserException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User successfully registered.
        /// </summary>
        public static string DialogTextNewUserSuccess {
            get {
                return ResourceManager.GetString("DialogTextNewUserSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Passwords do not match.
        /// </summary>
        public static string DialogTextPasswordsDontMatch {
            get {
                return ResourceManager.GetString("DialogTextPasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right Credentials.
        /// </summary>
        public static string DialogTextRightCredentials {
            get {
                return ResourceManager.GetString("DialogTextRightCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email is too short.
        /// </summary>
        public static string DialogTextShortEmail {
            get {
                return ResourceManager.GetString("DialogTextShortEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password is too short.
        /// </summary>
        public static string DialogTextShortPassword {
            get {
                return ResourceManager.GetString("DialogTextShortPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username is too short.
        /// </summary>
        public static string DialogTextShortUsername {
            get {
                return ResourceManager.GetString("DialogTextShortUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This username is already in use.
        /// </summary>
        public static string DialogTextUserAlreadyExists {
            get {
                return ResourceManager.GetString("DialogTextUserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrong Credentials.
        /// </summary>
        public static string DialogTextWrongCredentials {
            get {
                return ResourceManager.GetString("DialogTextWrongCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string es {
            get {
                return ResourceManager.GetString("es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Envido.
        /// </summary>
        public static string GameTextEnvido {
            get {
                return ResourceManager.GetString("GameTextEnvido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falta Envido.
        /// </summary>
        public static string GameTextFaltaEnvido {
            get {
                return ResourceManager.GetString("GameTextFaltaEnvido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Flor.
        /// </summary>
        public static string GameTextFlor {
            get {
                return ResourceManager.GetString("GameTextFlor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestures.
        /// </summary>
        public static string GameTextGestures {
            get {
                return ResourceManager.GetString("GameTextGestures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hand.
        /// </summary>
        public static string GameTextHand {
            get {
                return ResourceManager.GetString("GameTextHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I don&apos;t want.
        /// </summary>
        public static string GameTextIDontWant {
            get {
                return ResourceManager.GetString("GameTextIDontWant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I want.
        /// </summary>
        public static string GameTextIWant {
            get {
                return ResourceManager.GetString("GameTextIWant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leader.
        /// </summary>
        public static string GameTextLeader {
            get {
                return ResourceManager.GetString("GameTextLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play with friends.
        /// </summary>
        public static string GameTextPlayWithFriends {
            get {
                return ResourceManager.GetString("GameTextPlayWithFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quiero vale 4.
        /// </summary>
        public static string GameTextQuieroVale {
            get {
                return ResourceManager.GetString("GameTextQuieroVale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Real envido.
        /// </summary>
        public static string GameTextRealEnvido {
            get {
                return ResourceManager.GetString("GameTextRealEnvido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Retruco.
        /// </summary>
        public static string GameTextRetruco {
            get {
                return ResourceManager.GetString("GameTextRetruco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scoreboard.
        /// </summary>
        public static string GameTextScoreboard {
            get {
                return ResourceManager.GetString("GameTextScoreboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Truco.
        /// </summary>
        public static string GameTextTruco {
            get {
                return ResourceManager.GetString("GameTextTruco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string GlobalTextAccept {
            get {
                return ResourceManager.GetString("GlobalTextAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accepted.
        /// </summary>
        public static string GlobalTextAccepted {
            get {
                return ResourceManager.GetString("GlobalTextAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add friend.
        /// </summary>
        public static string GlobalTextAddFriend {
            get {
                return ResourceManager.GetString("GlobalTextAddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string GlobalTextBack {
            get {
                return ResourceManager.GetString("GlobalTextBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ban.
        /// </summary>
        public static string GlobalTextBan {
            get {
                return ResourceManager.GetString("GlobalTextBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Banned.
        /// </summary>
        public static string GlobalTextBanned {
            get {
                return ResourceManager.GetString("GlobalTextBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blocked.
        /// </summary>
        public static string GlobalTextBlocked {
            get {
                return ResourceManager.GetString("GlobalTextBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string GlobalTextCancel {
            get {
                return ResourceManager.GetString("GlobalTextCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change password.
        /// </summary>
        public static string GlobalTextChangePassword {
            get {
                return ResourceManager.GetString("GlobalTextChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm.
        /// </summary>
        public static string GlobalTextConfirm {
            get {
                return ResourceManager.GetString("GlobalTextConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmation.
        /// </summary>
        public static string GlobalTextConfirmation {
            get {
                return ResourceManager.GetString("GlobalTextConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm password.
        /// </summary>
        public static string GlobalTextConfirmPassword {
            get {
                return ResourceManager.GetString("GlobalTextConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create account.
        /// </summary>
        public static string GlobalTextCreateAccount {
            get {
                return ResourceManager.GetString("GlobalTextCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E-mail.
        /// </summary>
        public static string GlobalTextEmail {
            get {
                return ResourceManager.GetString("GlobalTextEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter code.
        /// </summary>
        public static string GlobalTextEnterCode {
            get {
                return ResourceManager.GetString("GlobalTextEnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        public static string GlobalTextExit {
            get {
                return ResourceManager.GetString("GlobalTextExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expired.
        /// </summary>
        public static string GlobalTextExpired {
            get {
                return ResourceManager.GetString("GlobalTextExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fill all the fields.
        /// </summary>
        public static string GlobalTextFillFields {
            get {
                return ResourceManager.GetString("GlobalTextFillFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finished.
        /// </summary>
        public static string GlobalTextFinished {
            get {
                return ResourceManager.GetString("GlobalTextFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends.
        /// </summary>
        public static string GlobalTextFriends {
            get {
                return ResourceManager.GetString("GlobalTextFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friendship.
        /// </summary>
        public static string GlobalTextFriendship {
            get {
                return ResourceManager.GetString("GlobalTextFriendship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hello.
        /// </summary>
        public static string GlobalTextHello {
            get {
                return ResourceManager.GetString("GlobalTextHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        public static string GlobalTextHome {
            get {
                return ResourceManager.GetString("GlobalTextHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a In progress.
        /// </summary>
        public static string GlobalTextInProgress {
            get {
                return ResourceManager.GetString("GlobalTextInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitation.
        /// </summary>
        public static string GlobalTextInvitation {
            get {
                return ResourceManager.GetString("GlobalTextInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a InviteFriend.
        /// </summary>
        public static string GlobalTextInviteFriend {
            get {
                return ResourceManager.GetString("GlobalTextInviteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lobby.
        /// </summary>
        public static string GlobalTextLobby {
            get {
                return ResourceManager.GetString("GlobalTextLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log out.
        /// </summary>
        public static string GlobalTextLogOut {
            get {
                return ResourceManager.GetString("GlobalTextLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Main menu.
        /// </summary>
        public static string GlobalTextMainMenu {
            get {
                return ResourceManager.GetString("GlobalTextMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string GlobalTextName {
            get {
                return ResourceManager.GetString("GlobalTextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create a new account.
        /// </summary>
        public static string GlobalTextNewUser {
            get {
                return ResourceManager.GetString("GlobalTextNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Next.
        /// </summary>
        public static string GlobalTextNext {
            get {
                return ResourceManager.GetString("GlobalTextNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Owner.
        /// </summary>
        public static string GlobalTextOwner {
            get {
                return ResourceManager.GetString("GlobalTextOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Party code.
        /// </summary>
        public static string GlobalTextPartyCode {
            get {
                return ResourceManager.GetString("GlobalTextPartyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string GlobalTextPassword {
            get {
                return ResourceManager.GetString("GlobalTextPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pending.
        /// </summary>
        public static string GlobalTextPending {
            get {
                return ResourceManager.GetString("GlobalTextPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player.
        /// </summary>
        public static string GlobalTextPlayer {
            get {
                return ResourceManager.GetString("GlobalTextPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        public static string GlobalTextProfile {
            get {
                return ResourceManager.GetString("GlobalTextProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rankings.
        /// </summary>
        public static string GlobalTextRankings {
            get {
                return ResourceManager.GetString("GlobalTextRankings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reason.
        /// </summary>
        public static string GlobalTextReason {
            get {
                return ResourceManager.GetString("GlobalTextReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register.
        /// </summary>
        public static string GlobalTextRegister {
            get {
                return ResourceManager.GetString("GlobalTextRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register new user.
        /// </summary>
        public static string GlobalTextRegisterNewUser {
            get {
                return ResourceManager.GetString("GlobalTextRegisterNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Round.
        /// </summary>
        public static string GlobalTextRound {
            get {
                return ResourceManager.GetString("GlobalTextRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string GlobalTextSave {
            get {
                return ResourceManager.GetString("GlobalTextSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Score.
        /// </summary>
        public static string GlobalTextScore {
            get {
                return ResourceManager.GetString("GlobalTextScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string GlobalTextSettings {
            get {
                return ResourceManager.GetString("GlobalTextSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start game.
        /// </summary>
        public static string GlobalTextStartGame {
            get {
                return ResourceManager.GetString("GlobalTextStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status.
        /// </summary>
        public static string GlobalTextStatus {
            get {
                return ResourceManager.GetString("GlobalTextStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success.
        /// </summary>
        public static string GlobalTextSuccess {
            get {
                return ResourceManager.GetString("GlobalTextSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Surnames.
        /// </summary>
        public static string GlobalTextSurnames {
            get {
                return ResourceManager.GetString("GlobalTextSurnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Global Top.
        /// </summary>
        public static string GlobalTextTop10 {
            get {
                return ResourceManager.GetString("GlobalTextTop10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Argentinian Truco.
        /// </summary>
        public static string GlobalTextTrucoArg {
            get {
                return ResourceManager.GetString("GlobalTextTrucoArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        public static string GlobalTextUser {
            get {
                return ResourceManager.GetString("GlobalTextUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string GlobalTextUsername {
            get {
                return ResourceManager.GetString("GlobalTextUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome.
        /// </summary>
        public static string GlobalTextWelcome {
            get {
                return ResourceManager.GetString("GlobalTextWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Winner.
        /// </summary>
        public static string GlobalTextWinner {
            get {
                return ResourceManager.GetString("GlobalTextWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wins.
        /// </summary>
        public static string GlobalTextWins {
            get {
                return ResourceManager.GetString("GlobalTextWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quit game.
        /// </summary>
        public static string MenuTextExit {
            get {
                return ResourceManager.GetString("MenuTextExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Match.
        /// </summary>
        public static string MenuTextMatch {
            get {
                return ResourceManager.GetString("MenuTextMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Avatar.
        /// </summary>
        public static string ProfileTextAvatar {
            get {
                return ResourceManager.GetString("ProfileTextAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm new password.
        /// </summary>
        public static string ProfileTextConfirmNewPassword {
            get {
                return ResourceManager.GetString("ProfileTextConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New password.
        /// </summary>
        public static string ProfileTextNewPassword {
            get {
                return ResourceManager.GetString("ProfileTextNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Social networks.
        /// </summary>
        public static string ProfileTextSocialNetworks {
            get {
                return ResourceManager.GetString("ProfileTextSocialNetworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last 5 games.
        /// </summary>
        public static string RankingsTextLastGames {
            get {
                return ResourceManager.GetString("RankingsTextLastGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        public static string SettingsTextAbout {
            get {
                return ResourceManager.GetString("SettingsTextAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credits.
        /// </summary>
        public static string SettingsTextCredits {
            get {
                return ResourceManager.GetString("SettingsTextCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string SettingsTextLanguage {
            get {
                return ResourceManager.GetString("SettingsTextLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select language.
        /// </summary>
        public static string SettingsTextSelectLanguage {
            get {
                return ResourceManager.GetString("SettingsTextSelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email or Username.
        /// </summary>
        public static string StarTextEmailOrUsername {
            get {
                return ResourceManager.GetString("StarTextEmailOrUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot password?.
        /// </summary>
        public static string StartTextForgotPassword {
            get {
                return ResourceManager.GetString("StartTextForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in.
        /// </summary>
        public static string StartTextLogIn {
            get {
                return ResourceManager.GetString("StartTextLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play as Guest.
        /// </summary>
        public static string StartTextPlayAsGuest {
            get {
                return ResourceManager.GetString("StartTextPlayAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sing up for free.
        /// </summary>
        public static string StartTextSingUp {
            get {
                return ResourceManager.GetString("StartTextSingUp", resourceCulture);
            }
        }
    }
}
