//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrucoPrueba1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthToken
    {
        public int tokenID { get; set; }
        public int userID { get; set; }
        public string refreshHash { get; set; }
        public System.DateTime expiresAt { get; set; }
    
        public virtual User User { get; set; }
    }
}
