//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrucoPrueba1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class baseDatosPruebaEntities : DbContext
    {
        public baseDatosPruebaEntities()
            : base("name=baseDatosPruebaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuthToken> AuthToken { get; set; }
        public virtual DbSet<Ban> Ban { get; set; }
        public virtual DbSet<BannedWord> BannedWord { get; set; }
        public virtual DbSet<Card> Card { get; set; }
        public virtual DbSet<DealtCard> DealtCard { get; set; }
        public virtual DbSet<Friendship> Friendship { get; set; }
        public virtual DbSet<Invitation> Invitation { get; set; }
        public virtual DbSet<Lobby> Lobby { get; set; }
        public virtual DbSet<LobbyMember> LobbyMember { get; set; }
        public virtual DbSet<Match> Match { get; set; }
        public virtual DbSet<MatchPlayer> MatchPlayer { get; set; }
        public virtual DbSet<Round> Round { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserProfile> UserProfile { get; set; }
        public virtual DbSet<Versions> Versions { get; set; }
    }
}
