//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrucoPrueba1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friendship
    {
        public int friendshipID { get; set; }
        public int userID { get; set; }
        public int friendID { get; set; }
        public string status { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
