//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrucoPrueba1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invitation
    {
        public int invitationID { get; set; }
        public int senderID { get; set; }
        public string receiverEmail { get; set; }
        public int code { get; set; }
        public string status { get; set; }
        public System.DateTime expiresAt { get; set; }
    
        public virtual User User { get; set; }
    }
}
