//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrucoPrueba1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lobby
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lobby()
        {
            this.LobbyMember = new HashSet<LobbyMember>();
            this.Match = new HashSet<Match>();
        }
    
        public int lobbyID { get; set; }
        public int ownerID { get; set; }
        public int versionID { get; set; }
        public int maxPlayers { get; set; }
    
        public virtual User User { get; set; }
        public virtual Versions Versions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LobbyMember> LobbyMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Match> Match { get; set; }
    }
}
