//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrucoPrueba1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchPlayer
    {
        public int matchID { get; set; }
        public int userID { get; set; }
        public string team { get; set; }
        public int score { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual User User { get; set; }
    }
}
