//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrucoPrueba1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Match()
        {
            this.MatchPlayer = new HashSet<MatchPlayer>();
            this.Round = new HashSet<Round>();
        }
    
        public int matchID { get; set; }
        public int lobbyID { get; set; }
        public int versionID { get; set; }
        public string status { get; set; }
        public System.DateTime startedAt { get; set; }
        public System.DateTime endedAt { get; set; }
    
        public virtual Lobby Lobby { get; set; }
        public virtual Versions Versions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchPlayer> MatchPlayer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Round> Round { get; set; }
    }
}
