//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrucoClient.TrucoServer
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserProfileData", Namespace="http://schemas.datacontract.org/2004/07/TrucoServer.Data.DTOs")]
    public partial class UserProfileData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AvatarIdField;
        
        private string EmailField;
        
        private string FacebookHandleField;
        
        private string InstagramHandleField;
        
        private bool IsMusicMutedField;
        
        private string LanguageCodeField;
        
        private int NameChangeCountField;
        
        private string UsernameField;
        
        private string XHandleField;

        private int PlayerIdField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerId
        {
            get { return this.PlayerIdField; }
            set { this.PlayerIdField = value; }
        }

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvatarId
        {
            get
            {
                return this.AvatarIdField;
            }
            set
            {
                this.AvatarIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacebookHandle
        {
            get
            {
                return this.FacebookHandleField;
            }
            set
            {
                this.FacebookHandleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstagramHandle
        {
            get
            {
                return this.InstagramHandleField;
            }
            set
            {
                this.InstagramHandleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMusicMuted
        {
            get
            {
                return this.IsMusicMutedField;
            }
            set
            {
                this.IsMusicMutedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LanguageCode
        {
            get
            {
                return this.LanguageCodeField;
            }
            set
            {
                this.LanguageCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NameChangeCount
        {
            get
            {
                return this.NameChangeCountField;
            }
            set
            {
                this.NameChangeCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XHandle
        {
            get
            {
                return this.XHandleField;
            }
            set
            {
                this.XHandleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerStatistics", Namespace="http://schemas.datacontract.org/2004/07/TrucoServer.Data.DTOs")]
    public partial class PlayerStatistics : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int LossesField;
        
        private string PlayerNameField;
        
        private int WinsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Losses
        {
            get
            {
                return this.LossesField;
            }
            set
            {
                this.LossesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerName
        {
            get
            {
                return this.PlayerNameField;
            }
            set
            {
                this.PlayerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Wins
        {
            get
            {
                return this.WinsField;
            }
            set
            {
                this.WinsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchScore", Namespace="http://schemas.datacontract.org/2004/07/TrucoServer.Data.DTOs")]
    public partial class MatchScore : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime EndedAtField;
        
        private int FinalScoreField;
        
        private bool IsWinField;
        
        private string MatchIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndedAt
        {
            get
            {
                return this.EndedAtField;
            }
            set
            {
                this.EndedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FinalScore
        {
            get
            {
                return this.FinalScoreField;
            }
            set
            {
                this.FinalScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsWin
        {
            get
            {
                return this.IsWinField;
            }
            set
            {
                this.IsWinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MatchID
        {
            get
            {
                return this.MatchIDField;
            }
            set
            {
                this.MatchIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PasswordResetOptions", Namespace="http://schemas.datacontract.org/2004/07/TrucoServer.Data.DTOs")]
    public partial class PasswordResetOptions : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodeField;
        
        private string EmailField;
        
        private string LanguageCodeField;
        
        private string NewPasswordField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LanguageCode
        {
            get
            {
                return this.LanguageCodeField;
            }
            set
            {
                this.LanguageCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewPassword
        {
            get
            {
                return this.NewPasswordField;
            }
            set
            {
                this.NewPasswordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerInformation", Namespace="http://schemas.datacontract.org/2004/07/TrucoServer.Data.DTOs")]
    public partial class PlayerInformation : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AvatarIdField;
        
        private string OwnerUsernameField;
        
        private string TeamField;
        
        private string UsernameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvatarId
        {
            get
            {
                return this.AvatarIdField;
            }
            set
            {
                this.AvatarIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OwnerUsername
        {
            get
            {
                return this.OwnerUsernameField;
            }
            set
            {
                this.OwnerUsernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Team
        {
            get
            {
                return this.TeamField;
            }
            set
            {
                this.TeamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrucoCard", Namespace="http://schemas.datacontract.org/2004/07/TrucoServer.GameLogic")]
    public partial class TrucoCard : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private TrucoClient.TrucoServer.Rank CardRankField;
        
        private TrucoClient.TrucoServer.Suit CardSuitField;
        
        private string FileNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrucoClient.TrucoServer.Rank CardRank
        {
            get
            {
                return this.CardRankField;
            }
            set
            {
                this.CardRankField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrucoClient.TrucoServer.Suit CardSuit
        {
            get
            {
                return this.CardSuitField;
            }
            set
            {
                this.CardSuitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rank", Namespace="http://schemas.datacontract.org/2004/07/TrucoServer.GameLogic")]
    public enum Rank : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Uno = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Dos = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tres = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cuatro = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cinco = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Seis = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Siete = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Diez = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Once = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Doce = 12,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Suit", Namespace="http://schemas.datacontract.org/2004/07/TrucoServer.GameLogic")]
    public enum Suit : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        club_ = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        cup_ = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        sword_ = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        gold_ = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/TrucoServer.Data.DTOs")]
    public partial class CustomFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ErrorCodeField;
        
        private string ErrorMessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PublicLobbyInformation", Namespace="http://schemas.datacontract.org/2004/07/TrucoServer.Data.DTOs")]
    public partial class PublicLobbyInformation : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CurrentPlayersField;
        
        private string MatchCodeField;
        
        private string MatchNameField;
        
        private int MaxPlayersField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentPlayers
        {
            get
            {
                return this.CurrentPlayersField;
            }
            set
            {
                this.CurrentPlayersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MatchCode
        {
            get
            {
                return this.MatchCodeField;
            }
            set
            {
                this.MatchCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MatchName
        {
            get
            {
                return this.MatchNameField;
            }
            set
            {
                this.MatchNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxPlayers
        {
            get
            {
                return this.MaxPlayersField;
            }
            set
            {
                this.MaxPlayersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BannedWordList", Namespace="http://schemas.datacontract.org/2004/07/TrucoServer.Data.DTOs")]
    public partial class BannedWordList : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string[] BannedWordsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] BannedWords
        {
            get
            {
                return this.BannedWordsField;
            }
            set
            {
                this.BannedWordsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InviteFriendOptions", Namespace="http://schemas.datacontract.org/2004/07/TrucoServer.Data.DTOs")]
    public partial class InviteFriendOptions : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FriendUsernameField;
        
        private string MatchCodeField;
        
        private string SenderUsernameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FriendUsername
        {
            get
            {
                return this.FriendUsernameField;
            }
            set
            {
                this.FriendUsernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MatchCode
        {
            get
            {
                return this.MatchCodeField;
            }
            set
            {
                this.MatchCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderUsername
        {
            get
            {
                return this.SenderUsernameField;
            }
            set
            {
                this.SenderUsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FriendData", Namespace="http://schemas.datacontract.org/2004/07/TrucoServer.Data.DTOs")]
    public partial class FriendData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AvatarIdField;
        
        private string UsernameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvatarId
        {
            get
            {
                return this.AvatarIdField;
            }
            set
            {
                this.AvatarIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TournamentDTO", Namespace="http://schemas.datacontract.org/2004/07/TrucoServer.Data.DTOs")]
    public partial class TournamentDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CapacityField;
        
        private int IdField;
        
        private string NameField;
        
        private string StatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Capacity
        {
            get
            {
                return this.CapacityField;
            }
            set
            {
                this.CapacityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BracketDTO", Namespace="http://schemas.datacontract.org/2004/07/TrucoServer.Data.DTOs")]
    public partial class BracketDTO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private string MatchIdField;
        
        private string Player1NameField;
        
        private string Player2NameField;
        
        private int PositionField;
        
        private int RoundField;
        
        private string WinnerNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MatchId
        {
            get
            {
                return this.MatchIdField;
            }
            set
            {
                this.MatchIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Player1Name
        {
            get
            {
                return this.Player1NameField;
            }
            set
            {
                this.Player1NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Player2Name
        {
            get
            {
                return this.Player2NameField;
            }
            set
            {
                this.Player2NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Position
        {
            get
            {
                return this.PositionField;
            }
            set
            {
                this.PositionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Round
        {
            get
            {
                return this.RoundField;
            }
            set
            {
                this.RoundField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WinnerName
        {
            get
            {
                return this.WinnerNameField;
            }
            set
            {
                this.WinnerNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TrucoClient.TrucoServer.ITrucoUserService", CallbackContract=typeof(TrucoClient.TrucoServer.ITrucoUserServiceCallback))]
    public interface ITrucoUserService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoUserService/RequestEmailVerification", ReplyAction="http://tempuri.org/ITrucoUserService/RequestEmailVerificationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TrucoClient.TrucoServer.CustomFault), Action="http://tempuri.org/ITrucoUserService/RequestEmailVerificationCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/TrucoServer.Data.DTOs")]
        bool RequestEmailVerification(string email, string languageCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoUserService/RequestEmailVerification", ReplyAction="http://tempuri.org/ITrucoUserService/RequestEmailVerificationResponse")]
        System.Threading.Tasks.Task<bool> RequestEmailVerificationAsync(string email, string languageCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoUserService/ConfirmEmailVerification", ReplyAction="http://tempuri.org/ITrucoUserService/ConfirmEmailVerificationResponse")]
        bool ConfirmEmailVerification(string email, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoUserService/ConfirmEmailVerification", ReplyAction="http://tempuri.org/ITrucoUserService/ConfirmEmailVerificationResponse")]
        System.Threading.Tasks.Task<bool> ConfirmEmailVerificationAsync(string email, string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoUserService/Register", ReplyAction="http://tempuri.org/ITrucoUserService/RegisterResponse")]
        bool Register(string username, string password, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoUserService/Register", ReplyAction="http://tempuri.org/ITrucoUserService/RegisterResponse")]
        System.Threading.Tasks.Task<bool> RegisterAsync(string username, string password, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoUserService/UsernameExists", ReplyAction="http://tempuri.org/ITrucoUserService/UsernameExistsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TrucoClient.TrucoServer.CustomFault), Action="http://tempuri.org/ITrucoUserService/UsernameExistsCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/TrucoServer.Data.DTOs")]
        bool UsernameExists(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoUserService/UsernameExists", ReplyAction="http://tempuri.org/ITrucoUserService/UsernameExistsResponse")]
        System.Threading.Tasks.Task<bool> UsernameExistsAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoUserService/EmailExists", ReplyAction="http://tempuri.org/ITrucoUserService/EmailExistsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TrucoClient.TrucoServer.CustomFault), Action="http://tempuri.org/ITrucoUserService/EmailExistsCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/TrucoServer.Data.DTOs")]
        bool EmailExists(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoUserService/EmailExists", ReplyAction="http://tempuri.org/ITrucoUserService/EmailExistsResponse")]
        System.Threading.Tasks.Task<bool> EmailExistsAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoUserService/Login", ReplyAction="http://tempuri.org/ITrucoUserService/LoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TrucoClient.TrucoServer.CustomFault), Action="http://tempuri.org/ITrucoUserService/LoginCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/TrucoServer.Data.DTOs")]
        bool Login(string username, string password, string languageCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoUserService/Login", ReplyAction="http://tempuri.org/ITrucoUserService/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string username, string password, string languageCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoUserService/UpdateUserAvatarAsync", ReplyAction="http://tempuri.org/ITrucoUserService/UpdateUserAvatarAsyncResponse")]
        bool UpdateUserAvatarAsync(string username, string newAvatarId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoUserService/UpdateUserAvatarAsync", ReplyAction="http://tempuri.org/ITrucoUserService/UpdateUserAvatarAsyncResponse")]
        System.Threading.Tasks.Task<bool> UpdateUserAvatarAsyncAsync(string username, string newAvatarId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoUserService/GetUserProfileByEmailAsync", ReplyAction="http://tempuri.org/ITrucoUserService/GetUserProfileByEmailAsyncResponse")]
        TrucoClient.TrucoServer.UserProfileData GetUserProfileByEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoUserService/GetUserProfileByEmailAsync", ReplyAction="http://tempuri.org/ITrucoUserService/GetUserProfileByEmailAsyncResponse")]
        System.Threading.Tasks.Task<TrucoClient.TrucoServer.UserProfileData> GetUserProfileByEmailAsyncAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoUserService/GetGlobalRanking", ReplyAction="http://tempuri.org/ITrucoUserService/GetGlobalRankingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TrucoClient.TrucoServer.CustomFault), Action="http://tempuri.org/ITrucoUserService/GetGlobalRankingCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/TrucoServer.Data.DTOs")]
        TrucoClient.TrucoServer.PlayerStatistics[] GetGlobalRanking();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoUserService/GetGlobalRanking", ReplyAction="http://tempuri.org/ITrucoUserService/GetGlobalRankingResponse")]
        System.Threading.Tasks.Task<TrucoClient.TrucoServer.PlayerStatistics[]> GetGlobalRankingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoUserService/GetLastMatches", ReplyAction="http://tempuri.org/ITrucoUserService/GetLastMatchesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TrucoClient.TrucoServer.CustomFault), Action="http://tempuri.org/ITrucoUserService/GetLastMatchesCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/TrucoServer.Data.DTOs")]
        TrucoClient.TrucoServer.MatchScore[] GetLastMatches(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoUserService/GetLastMatches", ReplyAction="http://tempuri.org/ITrucoUserService/GetLastMatchesResponse")]
        System.Threading.Tasks.Task<TrucoClient.TrucoServer.MatchScore[]> GetLastMatchesAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoUserService/GetUserProfile", ReplyAction="http://tempuri.org/ITrucoUserService/GetUserProfileResponse")]
        TrucoClient.TrucoServer.UserProfileData GetUserProfile(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoUserService/GetUserProfile", ReplyAction="http://tempuri.org/ITrucoUserService/GetUserProfileResponse")]
        System.Threading.Tasks.Task<TrucoClient.TrucoServer.UserProfileData> GetUserProfileAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoUserService/SaveUserProfile", ReplyAction="http://tempuri.org/ITrucoUserService/SaveUserProfileResponse")]
        bool SaveUserProfile(TrucoClient.TrucoServer.UserProfileData profile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoUserService/SaveUserProfile", ReplyAction="http://tempuri.org/ITrucoUserService/SaveUserProfileResponse")]
        System.Threading.Tasks.Task<bool> SaveUserProfileAsync(TrucoClient.TrucoServer.UserProfileData profile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoUserService/PasswordReset", ReplyAction="http://tempuri.org/ITrucoUserService/PasswordResetResponse")]
        bool PasswordReset(TrucoClient.TrucoServer.PasswordResetOptions options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoUserService/PasswordReset", ReplyAction="http://tempuri.org/ITrucoUserService/PasswordResetResponse")]
        System.Threading.Tasks.Task<bool> PasswordResetAsync(TrucoClient.TrucoServer.PasswordResetOptions options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoUserService/PasswordChange", ReplyAction="http://tempuri.org/ITrucoUserService/PasswordChangeResponse")]
        bool PasswordChange(string email, string newPassword, string languageCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoUserService/PasswordChange", ReplyAction="http://tempuri.org/ITrucoUserService/PasswordChangeResponse")]
        System.Threading.Tasks.Task<bool> PasswordChangeAsync(string email, string newPassword, string languageCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoUserService/LogClientException")]
        void LogClientException(string errorMessage, string stackTrace, string clientUsername);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoUserService/LogClientException")]
        System.Threading.Tasks.Task LogClientExceptionAsync(string errorMessage, string stackTrace, string clientUsername);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrucoUserServiceCallback
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoUserService/OnPlayerJoined")]
        void OnPlayerJoined(string matchCode, string player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoUserService/OnPlayerLeft")]
        void OnPlayerLeft(string matchCode, string player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoUserService/OnCardPlayed")]
        void OnCardPlayed(string matchCode, string player, string card);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoUserService/OnChatMessage")]
        void OnChatMessage(string matchCode, string player, string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoUserService/OnMatchStarted")]
        void OnMatchStarted(string matchCode, TrucoClient.TrucoServer.PlayerInformation[] players);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoUserService/OnMatchEnded")]
        void OnMatchEnded(string matchCode, string winner);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoUserService/OnFriendRequestReceived")]
        void OnFriendRequestReceived(string fromUser);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoUserService/OnFriendRequestAccepted")]
        void OnFriendRequestAccepted(string fromUser);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoUserService/ReceiveCards")]
        void ReceiveCards(TrucoClient.TrucoServer.TrucoCard[] hand);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoUserService/NotifyCardPlayed")]
        void NotifyCardPlayed(string playerName, string cardFileName, bool isLastCardOfRound);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoUserService/NotifyTurnChange")]
        void NotifyTurnChange(string nextPlayerName);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoUserService/NotifyScoreUpdate")]
        void NotifyScoreUpdate(int team1Score, int team2Score);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoUserService/NotifyTrucoCall")]
        void NotifyTrucoCall(string callerName, string betName, bool needsResponse);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoUserService/NotifyResponse")]
        void NotifyResponse(string responderName, string response, string newBetState);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoUserService/NotifyRoundEnd")]
        void NotifyRoundEnd(string winnerName, int team1Score, int team2Score);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoUserService/NotifyEnvidoCall")]
        void NotifyEnvidoCall(string callerName, string betName, bool needsResponse);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoUserService/NotifyEnvidoResult")]
        void NotifyEnvidoResult(string winnerName, int score, int totalPointsAwarded);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoUserService/NotifyFlorCall")]
        void NotifyFlorCall(string callerName, string betName, bool needsResponse);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoUserService/OnForcedLogout")]
        void OnForcedLogout();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoUserService/Ping", ReplyAction="http://tempuri.org/ITrucoUserService/PingResponse")]
        void Ping();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrucoUserServiceChannel : TrucoClient.TrucoServer.ITrucoUserService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrucoUserServiceClient : System.ServiceModel.DuplexClientBase<TrucoClient.TrucoServer.ITrucoUserService>, TrucoClient.TrucoServer.ITrucoUserService
    {
        
        public TrucoUserServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance)
        {
        }
        
        public TrucoUserServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName)
        {
        }
        
        public TrucoUserServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress)
        {
        }
        
        public TrucoUserServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress)
        {
        }
        
        public TrucoUserServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress)
        {
        }
        
        public bool RequestEmailVerification(string email, string languageCode)
        {
            return base.Channel.RequestEmailVerification(email, languageCode);
        }
        
        public System.Threading.Tasks.Task<bool> RequestEmailVerificationAsync(string email, string languageCode)
        {
            return base.Channel.RequestEmailVerificationAsync(email, languageCode);
        }
        
        public bool ConfirmEmailVerification(string email, string code)
        {
            return base.Channel.ConfirmEmailVerification(email, code);
        }
        
        public System.Threading.Tasks.Task<bool> ConfirmEmailVerificationAsync(string email, string code)
        {
            return base.Channel.ConfirmEmailVerificationAsync(email, code);
        }
        
        public bool Register(string username, string password, string email)
        {
            return base.Channel.Register(username, password, email);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterAsync(string username, string password, string email)
        {
            return base.Channel.RegisterAsync(username, password, email);
        }
        
        public bool UsernameExists(string username)
        {
            return base.Channel.UsernameExists(username);
        }
        
        public System.Threading.Tasks.Task<bool> UsernameExistsAsync(string username)
        {
            return base.Channel.UsernameExistsAsync(username);
        }
        
        public bool EmailExists(string email)
        {
            return base.Channel.EmailExists(email);
        }
        
        public System.Threading.Tasks.Task<bool> EmailExistsAsync(string email)
        {
            return base.Channel.EmailExistsAsync(email);
        }
        
        public bool Login(string username, string password, string languageCode)
        {
            return base.Channel.Login(username, password, languageCode);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string username, string password, string languageCode)
        {
            return base.Channel.LoginAsync(username, password, languageCode);
        }
        
        public bool UpdateUserAvatarAsync(string username, string newAvatarId)
        {
            return base.Channel.UpdateUserAvatarAsync(username, newAvatarId);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateUserAvatarAsyncAsync(string username, string newAvatarId)
        {
            return base.Channel.UpdateUserAvatarAsyncAsync(username, newAvatarId);
        }
        
        public TrucoClient.TrucoServer.UserProfileData GetUserProfileByEmailAsync(string email)
        {
            return base.Channel.GetUserProfileByEmailAsync(email);
        }
        
        public System.Threading.Tasks.Task<TrucoClient.TrucoServer.UserProfileData> GetUserProfileByEmailAsyncAsync(string email)
        {
            return base.Channel.GetUserProfileByEmailAsyncAsync(email);
        }
        
        public TrucoClient.TrucoServer.PlayerStatistics[] GetGlobalRanking()
        {
            return base.Channel.GetGlobalRanking();
        }
        
        public System.Threading.Tasks.Task<TrucoClient.TrucoServer.PlayerStatistics[]> GetGlobalRankingAsync()
        {
            return base.Channel.GetGlobalRankingAsync();
        }
        
        public TrucoClient.TrucoServer.MatchScore[] GetLastMatches(string username)
        {
            return base.Channel.GetLastMatches(username);
        }
        
        public System.Threading.Tasks.Task<TrucoClient.TrucoServer.MatchScore[]> GetLastMatchesAsync(string username)
        {
            return base.Channel.GetLastMatchesAsync(username);
        }
        
        public TrucoClient.TrucoServer.UserProfileData GetUserProfile(string username)
        {
            return base.Channel.GetUserProfile(username);
        }
        
        public System.Threading.Tasks.Task<TrucoClient.TrucoServer.UserProfileData> GetUserProfileAsync(string username)
        {
            return base.Channel.GetUserProfileAsync(username);
        }
        
        public bool SaveUserProfile(TrucoClient.TrucoServer.UserProfileData profile)
        {
            return base.Channel.SaveUserProfile(profile);
        }
        
        public System.Threading.Tasks.Task<bool> SaveUserProfileAsync(TrucoClient.TrucoServer.UserProfileData profile)
        {
            return base.Channel.SaveUserProfileAsync(profile);
        }
        
        public bool PasswordReset(TrucoClient.TrucoServer.PasswordResetOptions options)
        {
            return base.Channel.PasswordReset(options);
        }
        
        public System.Threading.Tasks.Task<bool> PasswordResetAsync(TrucoClient.TrucoServer.PasswordResetOptions options)
        {
            return base.Channel.PasswordResetAsync(options);
        }
        
        public bool PasswordChange(string email, string newPassword, string languageCode)
        {
            return base.Channel.PasswordChange(email, newPassword, languageCode);
        }
        
        public System.Threading.Tasks.Task<bool> PasswordChangeAsync(string email, string newPassword, string languageCode)
        {
            return base.Channel.PasswordChangeAsync(email, newPassword, languageCode);
        }
        
        public void LogClientException(string errorMessage, string stackTrace, string clientUsername)
        {
            base.Channel.LogClientException(errorMessage, stackTrace, clientUsername);
        }
        
        public System.Threading.Tasks.Task LogClientExceptionAsync(string errorMessage, string stackTrace, string clientUsername)
        {
            return base.Channel.LogClientExceptionAsync(errorMessage, stackTrace, clientUsername);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TrucoClient.TrucoServer.ITrucoMatchService", CallbackContract=typeof(TrucoClient.TrucoServer.ITrucoMatchServiceCallback))]
    public interface ITrucoMatchService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoMatchService/CreateLobby", ReplyAction="http://tempuri.org/ITrucoMatchService/CreateLobbyResponse")]
        string CreateLobby(string hostUsername, int maxPlayers, string privacy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoMatchService/CreateLobby", ReplyAction="http://tempuri.org/ITrucoMatchService/CreateLobbyResponse")]
        System.Threading.Tasks.Task<string> CreateLobbyAsync(string hostUsername, int maxPlayers, string privacy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoMatchService/JoinMatch", ReplyAction="http://tempuri.org/ITrucoMatchService/JoinMatchResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TrucoClient.TrucoServer.CustomFault), Action="http://tempuri.org/ITrucoMatchService/JoinMatchCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/TrucoServer.Data.DTOs")]
        int JoinMatch(string matchCode, string player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoMatchService/JoinMatch", ReplyAction="http://tempuri.org/ITrucoMatchService/JoinMatchResponse")]
        System.Threading.Tasks.Task<int> JoinMatchAsync(string matchCode, string player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/LeaveMatch")]
        void LeaveMatch(string matchCode, string player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/LeaveMatch")]
        System.Threading.Tasks.Task LeaveMatchAsync(string matchCode, string player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/JoinMatchChat")]
        void JoinMatchChat(string matchCode, string player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/JoinMatchChat")]
        System.Threading.Tasks.Task JoinMatchChatAsync(string matchCode, string player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/LeaveMatchChat")]
        void LeaveMatchChat(string matchCode, string player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/LeaveMatchChat")]
        System.Threading.Tasks.Task LeaveMatchChatAsync(string matchCode, string player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/SendChatMessage")]
        void SendChatMessage(string matchCode, string player, string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/SendChatMessage")]
        System.Threading.Tasks.Task SendChatMessageAsync(string matchCode, string player, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoMatchService/GetLobbyPlayers", ReplyAction="http://tempuri.org/ITrucoMatchService/GetLobbyPlayersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TrucoClient.TrucoServer.CustomFault), Action="http://tempuri.org/ITrucoMatchService/GetLobbyPlayersCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/TrucoServer.Data.DTOs")]
        TrucoClient.TrucoServer.PlayerInformation[] GetLobbyPlayers(string matchCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoMatchService/GetLobbyPlayers", ReplyAction="http://tempuri.org/ITrucoMatchService/GetLobbyPlayersResponse")]
        System.Threading.Tasks.Task<TrucoClient.TrucoServer.PlayerInformation[]> GetLobbyPlayersAsync(string matchCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoMatchService/GetPublicLobbies", ReplyAction="http://tempuri.org/ITrucoMatchService/GetPublicLobbiesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TrucoClient.TrucoServer.CustomFault), Action="http://tempuri.org/ITrucoMatchService/GetPublicLobbiesCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/TrucoServer.Data.DTOs")]
        TrucoClient.TrucoServer.PublicLobbyInformation[] GetPublicLobbies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoMatchService/GetPublicLobbies", ReplyAction="http://tempuri.org/ITrucoMatchService/GetPublicLobbiesResponse")]
        System.Threading.Tasks.Task<TrucoClient.TrucoServer.PublicLobbyInformation[]> GetPublicLobbiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoMatchService/SwitchTeam", ReplyAction="http://tempuri.org/ITrucoMatchService/SwitchTeamResponse")]
        void SwitchTeam(string matchCode, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoMatchService/SwitchTeam", ReplyAction="http://tempuri.org/ITrucoMatchService/SwitchTeamResponse")]
        System.Threading.Tasks.Task SwitchTeamAsync(string matchCode, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoMatchService/GetBannedWords", ReplyAction="http://tempuri.org/ITrucoMatchService/GetBannedWordsResponse")]
        TrucoClient.TrucoServer.BannedWordList GetBannedWords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoMatchService/GetBannedWords", ReplyAction="http://tempuri.org/ITrucoMatchService/GetBannedWordsResponse")]
        System.Threading.Tasks.Task<TrucoClient.TrucoServer.BannedWordList> GetBannedWordsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoMatchService/InviteFriend", ReplyAction="http://tempuri.org/ITrucoMatchService/InviteFriendResponse")]
        bool InviteFriend(TrucoClient.TrucoServer.InviteFriendOptions inviteContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoMatchService/InviteFriend", ReplyAction="http://tempuri.org/ITrucoMatchService/InviteFriendResponse")]
        System.Threading.Tasks.Task<bool> InviteFriendAsync(TrucoClient.TrucoServer.InviteFriendOptions inviteContext);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/StartMatch")]
        void StartMatch(string matchCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/StartMatch")]
        System.Threading.Tasks.Task StartMatchAsync(string matchCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/PlayCard")]
        void PlayCard(string matchCode, string cardFileName);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/PlayCard")]
        System.Threading.Tasks.Task PlayCardAsync(string matchCode, string cardFileName);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/CallTruco")]
        void CallTruco(string matchCode, string betType);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/CallTruco")]
        System.Threading.Tasks.Task CallTrucoAsync(string matchCode, string betType);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/RespondToCall")]
        void RespondToCall(string matchCode, string response);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/RespondToCall")]
        System.Threading.Tasks.Task RespondToCallAsync(string matchCode, string response);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/CallEnvido")]
        void CallEnvido(string matchCode, string betType);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/CallEnvido")]
        System.Threading.Tasks.Task CallEnvidoAsync(string matchCode, string betType);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/RespondToEnvido")]
        void RespondToEnvido(string matchCode, string response);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/RespondToEnvido")]
        System.Threading.Tasks.Task RespondToEnvidoAsync(string matchCode, string response);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/GoToDeck")]
        void GoToDeck(string matchCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/GoToDeck")]
        System.Threading.Tasks.Task GoToDeckAsync(string matchCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/CallFlor")]
        void CallFlor(string matchCode, string betType);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/CallFlor")]
        System.Threading.Tasks.Task CallFlorAsync(string matchCode, string betType);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/RespondToFlor")]
        void RespondToFlor(string matchCode, string response);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/RespondToFlor")]
        System.Threading.Tasks.Task RespondToFlorAsync(string matchCode, string response);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrucoMatchServiceCallback
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/OnPlayerJoined")]
        void OnPlayerJoined(string matchCode, string player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/OnPlayerLeft")]
        void OnPlayerLeft(string matchCode, string player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/OnCardPlayed")]
        void OnCardPlayed(string matchCode, string player, string card);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/OnChatMessage")]
        void OnChatMessage(string matchCode, string player, string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/OnMatchStarted")]
        void OnMatchStarted(string matchCode, TrucoClient.TrucoServer.PlayerInformation[] players);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/OnMatchEnded")]
        void OnMatchEnded(string matchCode, string winner);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/OnFriendRequestReceived")]
        void OnFriendRequestReceived(string fromUser);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/OnFriendRequestAccepted")]
        void OnFriendRequestAccepted(string fromUser);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/ReceiveCards")]
        void ReceiveCards(TrucoClient.TrucoServer.TrucoCard[] hand);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/NotifyCardPlayed")]
        void NotifyCardPlayed(string playerName, string cardFileName, bool isLastCardOfRound);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/NotifyTurnChange")]
        void NotifyTurnChange(string nextPlayerName);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/NotifyScoreUpdate")]
        void NotifyScoreUpdate(int team1Score, int team2Score);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/NotifyTrucoCall")]
        void NotifyTrucoCall(string callerName, string betName, bool needsResponse);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/NotifyResponse")]
        void NotifyResponse(string responderName, string response, string newBetState);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/NotifyRoundEnd")]
        void NotifyRoundEnd(string winnerName, int team1Score, int team2Score);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/NotifyEnvidoCall")]
        void NotifyEnvidoCall(string callerName, string betName, bool needsResponse);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/NotifyEnvidoResult")]
        void NotifyEnvidoResult(string winnerName, int score, int totalPointsAwarded);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/NotifyFlorCall")]
        void NotifyFlorCall(string callerName, string betName, bool needsResponse);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoMatchService/OnForcedLogout")]
        void OnForcedLogout();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoMatchService/Ping", ReplyAction="http://tempuri.org/ITrucoMatchService/PingResponse")]
        void Ping();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrucoMatchServiceChannel : TrucoClient.TrucoServer.ITrucoMatchService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrucoMatchServiceClient : System.ServiceModel.DuplexClientBase<TrucoClient.TrucoServer.ITrucoMatchService>, TrucoClient.TrucoServer.ITrucoMatchService
    {
        
        public TrucoMatchServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance)
        {
        }
        
        public TrucoMatchServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName)
        {
        }
        
        public TrucoMatchServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress)
        {
        }
        
        public TrucoMatchServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress)
        {
        }
        
        public TrucoMatchServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress)
        {
        }
        
        public string CreateLobby(string hostUsername, int maxPlayers, string privacy)
        {
            return base.Channel.CreateLobby(hostUsername, maxPlayers, privacy);
        }
        
        public System.Threading.Tasks.Task<string> CreateLobbyAsync(string hostUsername, int maxPlayers, string privacy)
        {
            return base.Channel.CreateLobbyAsync(hostUsername, maxPlayers, privacy);
        }
        
        public int JoinMatch(string matchCode, string player)
        {
            return base.Channel.JoinMatch(matchCode, player);
        }
        
        public System.Threading.Tasks.Task<int> JoinMatchAsync(string matchCode, string player)
        {
            return base.Channel.JoinMatchAsync(matchCode, player);
        }
        
        public void LeaveMatch(string matchCode, string player)
        {
            base.Channel.LeaveMatch(matchCode, player);
        }
        
        public System.Threading.Tasks.Task LeaveMatchAsync(string matchCode, string player)
        {
            return base.Channel.LeaveMatchAsync(matchCode, player);
        }
        
        public void JoinMatchChat(string matchCode, string player)
        {
            base.Channel.JoinMatchChat(matchCode, player);
        }
        
        public System.Threading.Tasks.Task JoinMatchChatAsync(string matchCode, string player)
        {
            return base.Channel.JoinMatchChatAsync(matchCode, player);
        }
        
        public void LeaveMatchChat(string matchCode, string player)
        {
            base.Channel.LeaveMatchChat(matchCode, player);
        }
        
        public System.Threading.Tasks.Task LeaveMatchChatAsync(string matchCode, string player)
        {
            return base.Channel.LeaveMatchChatAsync(matchCode, player);
        }
        
        public void SendChatMessage(string matchCode, string player, string message)
        {
            base.Channel.SendChatMessage(matchCode, player, message);
        }
        
        public System.Threading.Tasks.Task SendChatMessageAsync(string matchCode, string player, string message)
        {
            return base.Channel.SendChatMessageAsync(matchCode, player, message);
        }
        
        public TrucoClient.TrucoServer.PlayerInformation[] GetLobbyPlayers(string matchCode)
        {
            return base.Channel.GetLobbyPlayers(matchCode);
        }
        
        public System.Threading.Tasks.Task<TrucoClient.TrucoServer.PlayerInformation[]> GetLobbyPlayersAsync(string matchCode)
        {
            return base.Channel.GetLobbyPlayersAsync(matchCode);
        }
        
        public TrucoClient.TrucoServer.PublicLobbyInformation[] GetPublicLobbies()
        {
            return base.Channel.GetPublicLobbies();
        }
        
        public System.Threading.Tasks.Task<TrucoClient.TrucoServer.PublicLobbyInformation[]> GetPublicLobbiesAsync()
        {
            return base.Channel.GetPublicLobbiesAsync();
        }
        
        public void SwitchTeam(string matchCode, string username)
        {
            base.Channel.SwitchTeam(matchCode, username);
        }
        
        public System.Threading.Tasks.Task SwitchTeamAsync(string matchCode, string username)
        {
            return base.Channel.SwitchTeamAsync(matchCode, username);
        }
        
        public TrucoClient.TrucoServer.BannedWordList GetBannedWords()
        {
            return base.Channel.GetBannedWords();
        }
        
        public System.Threading.Tasks.Task<TrucoClient.TrucoServer.BannedWordList> GetBannedWordsAsync()
        {
            return base.Channel.GetBannedWordsAsync();
        }
        
        public bool InviteFriend(TrucoClient.TrucoServer.InviteFriendOptions inviteContext)
        {
            return base.Channel.InviteFriend(inviteContext);
        }
        
        public System.Threading.Tasks.Task<bool> InviteFriendAsync(TrucoClient.TrucoServer.InviteFriendOptions inviteContext)
        {
            return base.Channel.InviteFriendAsync(inviteContext);
        }
        
        public void StartMatch(string matchCode)
        {
            base.Channel.StartMatch(matchCode);
        }
        
        public System.Threading.Tasks.Task StartMatchAsync(string matchCode)
        {
            return base.Channel.StartMatchAsync(matchCode);
        }
        
        public void PlayCard(string matchCode, string cardFileName)
        {
            base.Channel.PlayCard(matchCode, cardFileName);
        }
        
        public System.Threading.Tasks.Task PlayCardAsync(string matchCode, string cardFileName)
        {
            return base.Channel.PlayCardAsync(matchCode, cardFileName);
        }
        
        public void CallTruco(string matchCode, string betType)
        {
            base.Channel.CallTruco(matchCode, betType);
        }
        
        public System.Threading.Tasks.Task CallTrucoAsync(string matchCode, string betType)
        {
            return base.Channel.CallTrucoAsync(matchCode, betType);
        }
        
        public void RespondToCall(string matchCode, string response)
        {
            base.Channel.RespondToCall(matchCode, response);
        }
        
        public System.Threading.Tasks.Task RespondToCallAsync(string matchCode, string response)
        {
            return base.Channel.RespondToCallAsync(matchCode, response);
        }
        
        public void CallEnvido(string matchCode, string betType)
        {
            base.Channel.CallEnvido(matchCode, betType);
        }
        
        public System.Threading.Tasks.Task CallEnvidoAsync(string matchCode, string betType)
        {
            return base.Channel.CallEnvidoAsync(matchCode, betType);
        }
        
        public void RespondToEnvido(string matchCode, string response)
        {
            base.Channel.RespondToEnvido(matchCode, response);
        }
        
        public System.Threading.Tasks.Task RespondToEnvidoAsync(string matchCode, string response)
        {
            return base.Channel.RespondToEnvidoAsync(matchCode, response);
        }
        
        public void GoToDeck(string matchCode)
        {
            base.Channel.GoToDeck(matchCode);
        }
        
        public System.Threading.Tasks.Task GoToDeckAsync(string matchCode)
        {
            return base.Channel.GoToDeckAsync(matchCode);
        }
        
        public void CallFlor(string matchCode, string betType)
        {
            base.Channel.CallFlor(matchCode, betType);
        }
        
        public System.Threading.Tasks.Task CallFlorAsync(string matchCode, string betType)
        {
            return base.Channel.CallFlorAsync(matchCode, betType);
        }
        
        public void RespondToFlor(string matchCode, string response)
        {
            base.Channel.RespondToFlor(matchCode, response);
        }
        
        public System.Threading.Tasks.Task RespondToFlorAsync(string matchCode, string response)
        {
            return base.Channel.RespondToFlorAsync(matchCode, response);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TrucoClient.TrucoServer.ITrucoFriendService", CallbackContract=typeof(TrucoClient.TrucoServer.ITrucoFriendServiceCallback))]
    public interface ITrucoFriendService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoFriendService/SendFriendRequest", ReplyAction="http://tempuri.org/ITrucoFriendService/SendFriendRequestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TrucoClient.TrucoServer.CustomFault), Action="http://tempuri.org/ITrucoFriendService/SendFriendRequestCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/TrucoServer.Data.DTOs")]
        bool SendFriendRequest(string fromUser, string toUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoFriendService/SendFriendRequest", ReplyAction="http://tempuri.org/ITrucoFriendService/SendFriendRequestResponse")]
        System.Threading.Tasks.Task<bool> SendFriendRequestAsync(string fromUser, string toUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoFriendService/AcceptFriendRequest", ReplyAction="http://tempuri.org/ITrucoFriendService/AcceptFriendRequestResponse")]
        bool AcceptFriendRequest(string fromUser, string toUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoFriendService/AcceptFriendRequest", ReplyAction="http://tempuri.org/ITrucoFriendService/AcceptFriendRequestResponse")]
        System.Threading.Tasks.Task<bool> AcceptFriendRequestAsync(string fromUser, string toUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoFriendService/RemoveFriendOrRequest", ReplyAction="http://tempuri.org/ITrucoFriendService/RemoveFriendOrRequestResponse")]
        bool RemoveFriendOrRequest(string user1, string user2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoFriendService/RemoveFriendOrRequest", ReplyAction="http://tempuri.org/ITrucoFriendService/RemoveFriendOrRequestResponse")]
        System.Threading.Tasks.Task<bool> RemoveFriendOrRequestAsync(string user1, string user2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoFriendService/GetFriends", ReplyAction="http://tempuri.org/ITrucoFriendService/GetFriendsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TrucoClient.TrucoServer.CustomFault), Action="http://tempuri.org/ITrucoFriendService/GetFriendsCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/TrucoServer.Data.DTOs")]
        TrucoClient.TrucoServer.FriendData[] GetFriends(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoFriendService/GetFriends", ReplyAction="http://tempuri.org/ITrucoFriendService/GetFriendsResponse")]
        System.Threading.Tasks.Task<TrucoClient.TrucoServer.FriendData[]> GetFriendsAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoFriendService/GetPendingFriendRequests", ReplyAction="http://tempuri.org/ITrucoFriendService/GetPendingFriendRequestsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TrucoClient.TrucoServer.CustomFault), Action="http://tempuri.org/ITrucoFriendService/GetPendingFriendRequestsCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/TrucoServer.Data.DTOs")]
        TrucoClient.TrucoServer.FriendData[] GetPendingFriendRequests(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoFriendService/GetPendingFriendRequests", ReplyAction="http://tempuri.org/ITrucoFriendService/GetPendingFriendRequestsResponse")]
        System.Threading.Tasks.Task<TrucoClient.TrucoServer.FriendData[]> GetPendingFriendRequestsAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrucoFriendServiceCallback
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoFriendService/OnPlayerJoined")]
        void OnPlayerJoined(string matchCode, string player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoFriendService/OnPlayerLeft")]
        void OnPlayerLeft(string matchCode, string player);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoFriendService/OnCardPlayed")]
        void OnCardPlayed(string matchCode, string player, string card);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoFriendService/OnChatMessage")]
        void OnChatMessage(string matchCode, string player, string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoFriendService/OnMatchStarted")]
        void OnMatchStarted(string matchCode, TrucoClient.TrucoServer.PlayerInformation[] players);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoFriendService/OnMatchEnded")]
        void OnMatchEnded(string matchCode, string winner);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoFriendService/OnFriendRequestReceived")]
        void OnFriendRequestReceived(string fromUser);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoFriendService/OnFriendRequestAccepted")]
        void OnFriendRequestAccepted(string fromUser);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoFriendService/ReceiveCards")]
        void ReceiveCards(TrucoClient.TrucoServer.TrucoCard[] hand);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoFriendService/NotifyCardPlayed")]
        void NotifyCardPlayed(string playerName, string cardFileName, bool isLastCardOfRound);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoFriendService/NotifyTurnChange")]
        void NotifyTurnChange(string nextPlayerName);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoFriendService/NotifyScoreUpdate")]
        void NotifyScoreUpdate(int team1Score, int team2Score);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoFriendService/NotifyTrucoCall")]
        void NotifyTrucoCall(string callerName, string betName, bool needsResponse);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoFriendService/NotifyResponse")]
        void NotifyResponse(string responderName, string response, string newBetState);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoFriendService/NotifyRoundEnd")]
        void NotifyRoundEnd(string winnerName, int team1Score, int team2Score);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoFriendService/NotifyEnvidoCall")]
        void NotifyEnvidoCall(string callerName, string betName, bool needsResponse);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoFriendService/NotifyEnvidoResult")]
        void NotifyEnvidoResult(string winnerName, int score, int totalPointsAwarded);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoFriendService/NotifyFlorCall")]
        void NotifyFlorCall(string callerName, string betName, bool needsResponse);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoFriendService/OnForcedLogout")]
        void OnForcedLogout();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoFriendService/Ping", ReplyAction="http://tempuri.org/ITrucoFriendService/PingResponse")]
        void Ping();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrucoFriendServiceChannel : TrucoClient.TrucoServer.ITrucoFriendService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrucoFriendServiceClient : System.ServiceModel.DuplexClientBase<TrucoClient.TrucoServer.ITrucoFriendService>, TrucoClient.TrucoServer.ITrucoFriendService
    {
        
        public TrucoFriendServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance)
        {
        }
        
        public TrucoFriendServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName)
        {
        }
        
        public TrucoFriendServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress)
        {
        }
        
        public TrucoFriendServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress)
        {
        }
        
        public TrucoFriendServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress)
        {
        }
        
        public bool SendFriendRequest(string fromUser, string toUser)
        {
            return base.Channel.SendFriendRequest(fromUser, toUser);
        }
        
        public System.Threading.Tasks.Task<bool> SendFriendRequestAsync(string fromUser, string toUser)
        {
            return base.Channel.SendFriendRequestAsync(fromUser, toUser);
        }
        
        public bool AcceptFriendRequest(string fromUser, string toUser)
        {
            return base.Channel.AcceptFriendRequest(fromUser, toUser);
        }
        
        public System.Threading.Tasks.Task<bool> AcceptFriendRequestAsync(string fromUser, string toUser)
        {
            return base.Channel.AcceptFriendRequestAsync(fromUser, toUser);
        }
        
        public bool RemoveFriendOrRequest(string user1, string user2)
        {
            return base.Channel.RemoveFriendOrRequest(user1, user2);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveFriendOrRequestAsync(string user1, string user2)
        {
            return base.Channel.RemoveFriendOrRequestAsync(user1, user2);
        }
        
        public TrucoClient.TrucoServer.FriendData[] GetFriends(string username)
        {
            return base.Channel.GetFriends(username);
        }
        
        public System.Threading.Tasks.Task<TrucoClient.TrucoServer.FriendData[]> GetFriendsAsync(string username)
        {
            return base.Channel.GetFriendsAsync(username);
        }
        
        public TrucoClient.TrucoServer.FriendData[] GetPendingFriendRequests(string username)
        {
            return base.Channel.GetPendingFriendRequests(username);
        }
        
        public System.Threading.Tasks.Task<TrucoClient.TrucoServer.FriendData[]> GetPendingFriendRequestsAsync(string username)
        {
            return base.Channel.GetPendingFriendRequestsAsync(username);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TrucoClient.TrucoServer.ITrucoTournamentService", CallbackContract=typeof(TrucoClient.TrucoServer.ITrucoTournamentServiceCallback))]
    public interface ITrucoTournamentService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoTournamentService/GetAvailableTournaments", ReplyAction="http://tempuri.org/ITrucoTournamentService/GetAvailableTournamentsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TrucoClient.TrucoServer.CustomFault), Action="http://tempuri.org/ITrucoTournamentService/GetAvailableTournamentsCustomFaultFaul" +
            "t", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/TrucoServer.Data.DTOs")]
        TrucoClient.TrucoServer.TournamentDTO[] GetAvailableTournaments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoTournamentService/GetAvailableTournaments", ReplyAction="http://tempuri.org/ITrucoTournamentService/GetAvailableTournamentsResponse")]
        System.Threading.Tasks.Task<TrucoClient.TrucoServer.TournamentDTO[]> GetAvailableTournamentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoTournamentService/SubscribeToTournament", ReplyAction="http://tempuri.org/ITrucoTournamentService/SubscribeToTournamentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TrucoClient.TrucoServer.CustomFault), Action="http://tempuri.org/ITrucoTournamentService/SubscribeToTournamentCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/TrucoServer.Data.DTOs")]
        bool SubscribeToTournament(int tournamentId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoTournamentService/SubscribeToTournament", ReplyAction="http://tempuri.org/ITrucoTournamentService/SubscribeToTournamentResponse")]
        System.Threading.Tasks.Task<bool> SubscribeToTournamentAsync(int tournamentId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoTournamentService/GetTournamentTree", ReplyAction="http://tempuri.org/ITrucoTournamentService/GetTournamentTreeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(TrucoClient.TrucoServer.CustomFault), Action="http://tempuri.org/ITrucoTournamentService/GetTournamentTreeCustomFaultFault", Name="CustomFault", Namespace="http://schemas.datacontract.org/2004/07/TrucoServer.Data.DTOs")]
        TrucoClient.TrucoServer.BracketDTO[] GetTournamentTree(int tournamentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITrucoTournamentService/GetTournamentTree", ReplyAction="http://tempuri.org/ITrucoTournamentService/GetTournamentTreeResponse")]
        System.Threading.Tasks.Task<TrucoClient.TrucoServer.BracketDTO[]> GetTournamentTreeAsync(int tournamentId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrucoTournamentServiceCallback
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoTournamentService/OnTournamentPlayerJoined")]
        void OnTournamentPlayerJoined(string username, int currentCapacity);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoTournamentService/OnTournamentStarted")]
        void OnTournamentStarted(TrucoClient.TrucoServer.BracketDTO[] initialBrackets);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITrucoTournamentService/OnBracketUpdated")]
        void OnBracketUpdated(TrucoClient.TrucoServer.BracketDTO updatedBracket);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITrucoTournamentServiceChannel : TrucoClient.TrucoServer.ITrucoTournamentService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrucoTournamentServiceClient : System.ServiceModel.DuplexClientBase<TrucoClient.TrucoServer.ITrucoTournamentService>, TrucoClient.TrucoServer.ITrucoTournamentService
    {
        
        public TrucoTournamentServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance)
        {
        }
        
        public TrucoTournamentServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName)
        {
        }
        
        public TrucoTournamentServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress)
        {
        }
        
        public TrucoTournamentServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress)
        {
        }
        
        public TrucoTournamentServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress)
        {
        }
        
        public TrucoClient.TrucoServer.TournamentDTO[] GetAvailableTournaments()
        {
            return base.Channel.GetAvailableTournaments();
        }
        
        public System.Threading.Tasks.Task<TrucoClient.TrucoServer.TournamentDTO[]> GetAvailableTournamentsAsync()
        {
            return base.Channel.GetAvailableTournamentsAsync();
        }
        
        public bool SubscribeToTournament(int tournamentId, int userId)
        {
            return base.Channel.SubscribeToTournament(tournamentId, userId);
        }
        
        public System.Threading.Tasks.Task<bool> SubscribeToTournamentAsync(int tournamentId, int userId)
        {
            return base.Channel.SubscribeToTournamentAsync(tournamentId, userId);
        }
        
        public TrucoClient.TrucoServer.BracketDTO[] GetTournamentTree(int tournamentId)
        {
            return base.Channel.GetTournamentTree(tournamentId);
        }
        
        public System.Threading.Tasks.Task<TrucoClient.TrucoServer.BracketDTO[]> GetTournamentTreeAsync(int tournamentId)
        {
            return base.Channel.GetTournamentTreeAsync(tournamentId);
        }
    }
}
